language: python
python:
  - "3.7"
install:
  - pip3 install -r requirements.txt
before_script:
  - python manage.py collectstatic --noinput
  - python manage.py migrate
script:
  - python3 manage.py test apps.spotify.test
