version: '3'

services:
  django:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/code #Para que el codigo se actualice en cada modificacion.
    ports:
      - "8000:8000"