version: '3'

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:${PORT} # El 0.0.0.0 significa que podemos acceder al sitio desde cualquier direccion del host,
    # pero para poder usar OAuth2 entraremos con 127.0.0.1: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/django
    restart: always
    container_name: django