# Generated by Django 3.0.4 on 2020-03-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('views', models.IntegerField(default=0, null=True)),
                ('date', models.DateTimeField(null=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('auth_url', models.CharField(default=None, max_length=200)),
                ('access_token', models.CharField(default=None, max_length=200)),
                ('refresh_token', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('duration', models.IntegerField(default=0, null=True)),
                ('song', models.ManyToManyField(to='spotify.Song')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('views', models.IntegerField(default=0, null=True)),
                ('information', models.CharField(default='No Artist Information', max_length=200, null=True)),
                ('song', models.ManyToManyField(to='spotify.Song')),
            ],
        ),
    ]
