# Generated by Django 3.0.6 on 2020-05-09 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('rate', models.IntegerField(default=0, null=True)),
                ('information', models.CharField(default='No Artist Information', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spotify_User',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=200, null=True)),
                ('refresh_token', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('rate', models.IntegerField(default=0, null=True)),
                ('date', models.DateTimeField(null=True, verbose_name='Publication date')),
                ('artist', models.ManyToManyField(to='spotify.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('duration', models.IntegerField(default=0, null=True)),
                ('is_local', models.BooleanField(default=False)),
                ('songs', models.ManyToManyField(to='spotify.Song')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spotify.Spotify_User')),
            ],
        ),
    ]
