# Generated by Django 3.0.4 on 2020-03-24 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_auto_20200323_1623'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
