# Generated by Django 3.0.4 on 2020-03-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spotify_User',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
