# Generated by Django 3.0.4 on 2020-03-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_song_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='views',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
