# Generated by Django 3.0.4 on 2020-03-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_spotify_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotify_user',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
