# Generated by Django 3.0.4 on 2020-03-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_auto_20200321_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('duration', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.AddField(
            model_name='artist',
            name='information',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='views',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
