# Generated by Django 3.0.4 on 2020-03-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0008_playlist_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='song',
        ),
        migrations.AddField(
            model_name='artist',
            name='song',
            field=models.ManyToManyField(to='spotify.Song'),
        ),
    ]
