# Generated by Django 3.0.4 on 2020-03-27 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0010_auto_20200326_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='songs',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spotify.Artist'),
        ),
        migrations.AlterField(
            model_name='spotify_user',
            name='playlists',
            field=models.ManyToManyField(to='spotify.Playlist'),
        ),
    ]
