# Generated by Django 3.0.4 on 2020-03-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0012_auto_20200327_0133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='views',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='views',
            new_name='rate',
        ),
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(to='spotify.Artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
