# Generated by Django 3.0.5 on 2020-05-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0013_auto_20200327_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_local',
            field=models.BooleanField(default=False),
        ),
    ]
